-- Generated By protoc-gen-lua Do not Edit
require "Protobuf.rpc_pb"
require "Protobuf.game_def_pb"
require "Protobuf.rpc_acc_pb"
require "Protobuf.rpc_acc_def_pb"
require "Protobuf.rpc_base_pb"
require "Protobuf.rpc_cs_pb"
require "Protobuf.rpc_cg_pb"
require "Protobuf.rpc_safebox_pb"
module('rpc', package.seeall)

-- game_def_pb
ClientDeviceType =
{
    CDT_Unknown = 0,
    CDT_IOS = 1,
    CDT_Android = 2,
    CDT_WebPlayer = 3,
    CDT_Windows = 4,
    CDT_MacOS = 5,
}

PlayerAttrType =
{
    PAT_BindSafebox = 1,                    -- 
}

ErrorCode =
{
    EC_Unknown        = -1,                --未知错误
    EC_Success        = 0 ,            --有时候内嵌在其他消息里面用，但是一般不用这个，如果成功的话
    EC_LackDiamond        = 1,            --钻石不足
    
    EC_WrongSelectTimes     = 2,            --倍数错误
    EC_WrongGameId        = 3,            --游戏房间已经关闭
    EC_WrongSelectLineCount = 4,            --选择线路的条数错误
    EC_CurrencyMax        = 7,            --对方资源达到上限
    EC_PlayerNotOnline    = 9,            --玩家不在线
    EC_MessageNotRight    = 10,            --消息ID不存在或者本消条消息已过期
    EC_JoinRoomDiamond    = 43,            --加入房间 ，钻石不足
}

GameType =
{
    GT_Fruit=1,--水果机
    GT_KingGlory=2,--王者荣耀
    RT_ThreeKindoms=3,--三国志
    RT_StreetFighter = 4,    --街霸
    RT_LOL        = 5,  --英雄联盟
    RT_Zombie    = 6,    -- 打僵尸
    RT_BattleGrounds = 7,        --绝地求生
    RT_fish = 8,        --捕鱼
    RT_Mammon    = 9,  --财神
}

EntityType =
{
    ET_Normal = 1,
    ET_Variable = 2,
    ET_FreeTimes = 3,
    ET_LittleGame = 4,
    ET_Lottery = 5,
}

SpecialEventType =
{
    SET_FreeGame    = 1,
    SET_LittleGame    = 2,
    SET_Lottery    = 3,
}

-- rpc_acc_pb
EAccountType =
{
    EAT_Unknown = 0,
    EAT_Internal = 1,        -- 内部服务器
    EAT_FeiDou = 2,            -- 飞豆(开心，神之背叛
    EAT_LeYou = 3,            -- 天创乐游
    EAT_LeYouAppStore = 4,    -- 天创乐游 for appStore
    EAT_Momo = 5,            -- 陌陌
    EAT_UCAndroid = 6,        -- UC Android
    EAT_360 = 7,
    EAT_XiaoMi = 8,
    EAT_YiJie = 9,            -- 易接SDK 鸣镝
    EAT_PPS = 10,
    EAT_TX = 11,            -- 腾讯（QQ、微信登录统一使用腾讯）
    EAT_QQ = 12,
    EAT_WeiXin = 13,
    EAT_BaiDu = 14,            
    EAT_Oppo = 15,
    EAT_LianXiang = 16,
    EAT_HuaWei = 17,
    EAT_Vivo = 18,
    EAT_JinLi = 19,
    EAT_KuPai = 20,
    EAT_YiJie_LinYou = 21,-- 易接SDK 麟游
    EAT_LengJing = 22,        -- 棱镜SDK
    EAT_BaiDu91 = 23,
    EAT_LinYou = 24,        
    EAT_FeiDouJP = 25,    --开心（日本）    
    EAT_9377 = 26,
    EAT_FeiDouEN = 27,    --开心（东南亚）
    EAT_FeiDouKOR = 28,    --开心（韩国）
    EAT_D = 29,            --当乐
    EAT_YiWan = 30,        --益玩
    EAT_WeiXinOpen = 31, -- 微信开放平台
}

-- rpc_acc_def_pb
LogoutReason =
{
    LR_Normal = 0,
    LR_RepeatedLogin = 1,
}

-- rpc_cg_pb
AuthResult =
{
    AR_OK = 0,                    -- 成功
    AR_Fail = 1,                -- 一般失败
    AR_MaxClient = 2,            -- 网络连接已满
    AR_RepeatedLogin = 3,        -- 重复登录
    AR_TokenInvalid = 4,        -- token无效
    AR_InputError = 5,            -- 输入格式错误
    AR_DisableLogin = 6,        -- 禁止登录
    AR_GameServerErr = 7,        -- 游戏服务器出错
    AR_AccountServerErr = 8,    -- 帐号服务器出错
    AR_VersionErr = 9,            -- 版本不匹配
    AR_GameServerNotOpen = 10,    -- 游戏服务器未开放
}

ReconnectResult =
{
    RR_OK = 0,
    RR_Fail    = 1,
    RR_MaxClient = 2,
}

-- rpc_safebox_pb
SendAuthcodeResult =
{
    SAR_Unknown = 1,
    SAR_Ok = 2,
    SAR_PhoneInValid = 3,
    SAR_PhoneNotFirstBind = 4,    -- 非首次绑定的电话号码(重新绑定时)
}

BindPhoneResult =
{
    BPR_Unknown = 0,
    BPR_Ok = 1,
    BPR_PasswordInvalid = 2,
    BPR_AuthCodeInvalid = 3,
}


-- rpc_pb
Request = rpc_pb.Request

-- rpc_acc_pb
LoginArgs = rpc_acc_pb.LoginArgs
LoginInfo = rpc_acc_pb.LoginInfo
LoginInfoWithAccount = rpc_acc_pb.LoginInfoWithAccount
C2S_AuthLogin = rpc_acc_pb.C2S_AuthLogin
C2S_Logout = rpc_acc_pb.C2S_Logout
C2S_PlayerReconnect = rpc_acc_pb.C2S_PlayerReconnect

-- rpc_acc_def_pb
S2C_Logout = rpc_acc_def_pb.S2C_Logout

-- rpc_base_pb
PlayerAttribute = rpc_base_pb.PlayerAttribute
PlayerBaseInfo = rpc_base_pb.PlayerBaseInfo
GameItemInfo = rpc_base_pb.GameItemInfo
FreePlayInfo = rpc_base_pb.FreePlayInfo
lineScore = rpc_base_pb.lineScore
LotteryItem = rpc_base_pb.LotteryItem
LotteryInfo = rpc_base_pb.LotteryInfo

-- rpc_cs_pb
C2S_Time = rpc_cs_pb.C2S_Time
S2C_Time = rpc_cs_pb.S2C_Time
S2C_LoginedPlayerInfo = rpc_cs_pb.S2C_LoginedPlayerInfo
S2C_ModifyPlayerAttr = rpc_cs_pb.S2C_ModifyPlayerAttr
GmCommond = rpc_cs_pb.GmCommond
S2C_Error = rpc_cs_pb.S2C_Error
C2S_SystemMessageTitleList = rpc_cs_pb.C2S_SystemMessageTitleList
SystemMessageTitleInfo = rpc_cs_pb.SystemMessageTitleInfo
S2C_SystemMessageTitleList = rpc_cs_pb.S2C_SystemMessageTitleList
C2S_SystemOneMessage = rpc_cs_pb.C2S_SystemOneMessage
S2C_SystemOneMessage = rpc_cs_pb.S2C_SystemOneMessage
S2C_DiamondModify = rpc_cs_pb.S2C_DiamondModify
S2C_NewSysMsg = rpc_cs_pb.S2C_NewSysMsg
S2C_NewRollMsg = rpc_cs_pb.S2C_NewRollMsg
C2S_GetGames = rpc_cs_pb.C2S_GetGames
S2C_GetGames = rpc_cs_pb.S2C_GetGames
C2S_EnterGame = rpc_cs_pb.C2S_EnterGame
S2C_EnterGame = rpc_cs_pb.S2C_EnterGame
C2S_LeaveGame = rpc_cs_pb.C2S_LeaveGame
C2S_PlayOnce = rpc_cs_pb.C2S_PlayOnce
S2C_PlayOnce = rpc_cs_pb.S2C_PlayOnce
UiSwitchItem = rpc_cs_pb.UiSwitchItem
S2C_UiSwitch = rpc_cs_pb.S2C_UiSwitch

-- rpc_cg_pb
C2S_Ping = rpc_cg_pb.C2S_Ping
S2C_Ping = rpc_cg_pb.S2C_Ping
S2C_AuthLogin = rpc_cg_pb.S2C_AuthLogin
S2C_PlayerReconnect = rpc_cg_pb.S2C_PlayerReconnect

-- rpc_safebox_pb
C2S_SendBindAuthCode = rpc_safebox_pb.C2S_SendBindAuthCode
S2C_SendBindAuthCode = rpc_safebox_pb.S2C_SendBindAuthCode
C2S_BindPhone = rpc_safebox_pb.C2S_BindPhone
S2C_BindPhone = rpc_safebox_pb.S2C_BindPhone
C2S_OpenSafeBox = rpc_safebox_pb.C2S_OpenSafeBox
S2C_OpenSafeBox = rpc_safebox_pb.S2C_OpenSafeBox
C2S_MoveToSafeBox = rpc_safebox_pb.C2S_MoveToSafeBox
S2C_MoveToSafeBox = rpc_safebox_pb.S2C_MoveToSafeBox
