-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('rpc_pb', package.seeall)
local pb_table = {}

pb_table.REQUEST = protobuf.Descriptor();
pb_table.REQUEST_METHOD_FIELD = protobuf.FieldDescriptor();
pb_table.REQUEST_SERIALIZED_REQUEST_FIELD = protobuf.FieldDescriptor();

pb_table.REQUEST_METHOD_FIELD.name = "method"
pb_table.REQUEST_METHOD_FIELD.full_name = ".rpc.Request.method"
pb_table.REQUEST_METHOD_FIELD.number = 1
pb_table.REQUEST_METHOD_FIELD.index = 0
pb_table.REQUEST_METHOD_FIELD.label = 2
pb_table.REQUEST_METHOD_FIELD.has_default_value = false
pb_table.REQUEST_METHOD_FIELD.default_value = ""
pb_table.REQUEST_METHOD_FIELD.type = 9
pb_table.REQUEST_METHOD_FIELD.cpp_type = 9

pb_table.REQUEST_SERIALIZED_REQUEST_FIELD.name = "serialized_request"
pb_table.REQUEST_SERIALIZED_REQUEST_FIELD.full_name = ".rpc.Request.serialized_request"
pb_table.REQUEST_SERIALIZED_REQUEST_FIELD.number = 2
pb_table.REQUEST_SERIALIZED_REQUEST_FIELD.index = 1
pb_table.REQUEST_SERIALIZED_REQUEST_FIELD.label = 1
pb_table.REQUEST_SERIALIZED_REQUEST_FIELD.has_default_value = false
pb_table.REQUEST_SERIALIZED_REQUEST_FIELD.default_value = ""
pb_table.REQUEST_SERIALIZED_REQUEST_FIELD.type = 12
pb_table.REQUEST_SERIALIZED_REQUEST_FIELD.cpp_type = 9

pb_table.REQUEST.name = "Request"
pb_table.REQUEST.full_name = ".rpc.Request"
pb_table.REQUEST.nested_types = {}
pb_table.REQUEST.enum_types = {}
pb_table.REQUEST.fields = {pb_table.REQUEST_METHOD_FIELD, pb_table.REQUEST_SERIALIZED_REQUEST_FIELD}
pb_table.REQUEST.is_extendable = false
pb_table.REQUEST.extensions = {}

Request = protobuf.Message(pb_table.REQUEST)

_G["RPC_PB_REQUEST"] = pb_table.REQUEST
